export const DASHBOARD_TABLE_DATA = [
    {user: "Michael", icon: "glyphicon glyphicon-home", repeat:true, date: "27.10.2018", title: "Miete", description: "Monatsmiete", price: 500, category:"haushalt"},
    {user: "Michael", icon: "glyphicon glyphicon-home", repeat:true, date: "27.11.2018", title: "Miete", description: "Monatsmiete", price: 500, category:"haushalt"},
    {user: "Markus",icon: "glyphicon glyphicon-cutlery", repeat:false, date: "24.10.2018", title: "Einkauf Essen Spar", description: "Brot, Butter, Milch, Eier", price: 99.01, category:"essen"},
    {user: "Gerhard", icon: "fas fa-futbol", repeat:false, date: "21.10.2018", title: "Eintritt Bouldern", price: 8.8, category:"freizeit"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "19.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "20.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Michael", icon: "glyphicon glyphicon-home", repeat:true, date: "21.10.2018", title: "Reinigung", price: 60, category:"haushalt"},
    {user: "Markus", icon: "fa fa-futbol", repeat:false, date: "22.10.2018", title: "Weihnachtsfeier", price: 120, category:"freizeit"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "23.10.2018", title: "Taxi nachm saufen", price: 25, category:"transport"},
    {user: "Matthias", icon: "fa fa-futbol", repeat:false, date: "24.10.2018", title: "Theaterkarten", price: 120, category:"freizeit"},
    {user: "Markus", icon: "fa fa-futbol", repeat:false, date: "25.10.2018", title: "Fußball-Spiel", price: 100, category:"freizeit"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "26.10.2018", title: "Ticket Bahn", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "27.10.2018", title: "Ticket Bus", price: 2, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "28.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "29.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "30.10.2018", title: "U-Bahn Ticket", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "27.10.2018", title: "Flug Mauritius", price: 400, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "28.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "29.10.2018", title: "Bus", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "30.10.2018", title: "Uber", price: 8, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "03.11.2018", title: "Taxi", price: 15, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "04.11.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "05.11.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Michael", icon: "glyphicon glyphicon-home", repeat:true, date: "21.11.2018", title: "Reinigung", price: 60, category:"haushalt"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "06.11.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "29.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "30.10.2018", title: "Ticket U-Bahn", price: 2, category:"transport"},
    {user: "Markus", icon: "glyphicon glyphicon-cutlery", repeat:false, date: "31.10.2018", title: "Einkauf", price: 45, category:"essen"},
    {user: "Gerhard", icon: "glyphicon glyphicon-home", repeat:false, date: "01.11.2018", title: "neuer Tisch", price: 250, category:"haushalt"},
    {user: "Matthias", icon: "glyphicon glyphicon-home", repeat:false, date: "02.11.2018", title: "lampe", price: 69, category:"haushalt"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "03.11.2018", title: "Benzin für Auto", price: 30, category:"transport"},
    {user: "Gerhard", icon: "glyphicon glyphicon-cutlery", repeat:false, date: "04.11.2018", title: "Essen bestellen für alle", price: 55, category:"essen"},
    {user: "Matthias", icon: "fa fa-futbol", repeat:false, date: "05.11.2018", title: "neues PS4 spiel", price: 60, category:"freizeit"},
    {user: "Markus", icon: "fa fa-futbol", repeat:false, date: "06.11.2018", title: "Kino", price: 40, category:"freizeit"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "07.11.2018", title: "Ticket U-Bahn", price: 2, category:"transport"}];

export const DATE_FORMAT = "DD.MM.YYYY";