export const DASHBOARD_TABLE_DATA = [
    {user: "Michael", icon: "glyphicon glyphicon-home", repeat:true, date: "27.10.2018", title: "Miete", description: "Monatsmiete", price: 50, category:"haushalt"},
    {user: "Markus",icon: "glyphicon glyphicon-cutlery", repeat:false, date: "24.10.2018", title: "Einkauf Essen Spar", description: "Brot, Butter, Milch, Eier", price: 99.01, category:"essen"},
    {user: "Gerhard", icon: "fas fa-futbol", repeat:false, date: "21.10.2018", title: "Eintritt Bouldern", price: 8.8, category:"freizeit"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "19.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "20.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Michael", icon: "fa fa-bus", repeat:false, date: "21.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "22.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "23.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "24.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "25.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "26.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "27.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "28.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "29.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "30.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "31.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "01.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "02.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "03.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "04.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Matthias", icon: "fa fa-bus", repeat:false, date: "05.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Markus", icon: "fa fa-bus", repeat:false, date: "06.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {user: "Gerhard", icon: "fa fa-bus", repeat:false, date: "07.11.2018", title: "Ticket U-Bahn", price: 10, category:"transport"}];

export const DATE_FORMAT = "dd.mm.yyyy";