export const DASHBOARD_TABLE_DATA = [
    {icon: "glyphicon glyphicon-home", repeat:true, date: "27.10.2018", title: "Miete", description: "Monatsmiete", price: 50, category:"haushalt"},
    {icon: "glyphicon glyphicon-cutlery", repeat:false, date: "24.10.2018", title: "Einkauf Essen Spar", description: "Brot, Butter, Milch, Eier", price: 99.01, category:"Essen"},
    {icon: "fas fa-futbol", repeat:false, date: "21.10.2018", title: "Eintritt Bouldern", price: 8.8, category:"freizeit"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"},
    {icon: "fa fa-bus", repeat:false, date: "18.10.2018", title: "Ticket U-Bahn", price: 10, category:"transport"}];

export const DATE_FORMAT = "dd.mm.yyyy";